Repository selsa-inube/inubekit-fieldset, pull requests merged in 2024-02, with the labels that each got.

#1 inubekit-fieldset: Create component `<Fieldset/>`
  package-lock.json
  package.json
  src/Fieldset/index.tsx
  src/Fieldset/props.ts
  src/Fieldset/stories/Fieldset.stories.tsx
  src/Fieldset/stories/styles.js
  src/Fieldset/styles.js
  src/index.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement, minor

#2 Release new version 0.1.0
  CHANGELOG.md
Labels: documentation

#6 Set the build to dist/, we are including the react runtime
  .storybook/main.ts
  package-lock.json
  package.json
  vite.config.ts
Labels: patch, dependencies

#7 Publish new version 0.2.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
